### PR TITLE
manage: force Python3 usage

### PR DESCRIPTION
**Pull request by greut**
This is a test for Hound (let me know if this was not the correct repository)

### CODE REVIEW

**Comment by Zegorax** [comment]
Hello Yoan, yes I activated Hound yesterday.

**Comment by Zegorax** [comment]
However, Hound will activate only if you modify JS or Python code in your PR.

**Comment by greut** [comment]
> Hello Yoan, yes I activated Hound yesterday.

You asked for it, I've activated it for this project this morning. Have fun!

**Comment by Zegorax** [comment]
It showed up as a request ? For me it was instantly activated yesterday already

**Comment by greut** [comment]
> It showed up as a request ?
Yes

>  For me it was instantly activated yesterday already
It was probably not.

**Comment by Zegorax** [comment]
Okay, I must have misread it then. Thanks :)

**Pull request closed without merging**
